# Generated by Django 3.2.2 on 2021-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsrData',
        ),
        migrations.AddField(
            model_name='user',
            name='email_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.TextField(blank=True),
        ),
    ]
