# Generated by Django 3.2.2 on 2021-10-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0007_user_reqcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reqCount',
            field=models.IntegerField(),
        ),
    ]
